### ISSUE TITLE
Support layers & provided runtimes

### ISSUE THREAD

**Issue by shouze** [inextensodigital/terraform-aws-lambda#8]
# Context

We currently use officially provided & supported AWS runtimes... but as we have php experts, we would like to run it on lambda too.

Due to the lack of official support, we will use [bef.sh](https://bref.sh/docs/).

We already support runtime configuration through an exposed variable:
https://github.com/inextensodigital/terraform-aws-lambda/blob/70aa534e4ad848198e2471c713fa94b04035cd09/variables.tf#L52-L56

# Todo

- [ ] Add support for layers by exposing a **layers** (list) variable
- [ ] Make a POC by using this module on a very simple php app (see next: PHP App). ⚠️ Don't forget to set runtime value to **provided** [as documented](https://docs.aws.amazon.com/lambda/latest/dg/runtimes-custom.html#runtimes-custom-use).
- [ ] **Bonus**: this module lacks of [`CI`](https://en.wikipedia.org/wiki/Continuous_integration), you can create a `.github/workflows/ci.yml` (see [Github Action doc](https://help.github.com/en/actions/automating-your-workflow-with-github-actions) and take inspiration from [some other terraform module's ci](https://github.com/terraform-aws-modules/terraform-aws-vpc/blob/master/.circleci/config.yml#L8-L38))

# Php App

the goal is to randomly generate a project code name and to echo it.

A project code name is generated as follow:
```
<ADJECTIVE> <NOUN>
```

Examples:
- Xenial Xerus
- Bionic Beaver
- Disco Dingo
- ...

💡 You can download adjectives & nouns lists [here](http://www.ashley-bovan.co.uk/words/partsofspeech.html)

So, index.php should looks like:
```php
<?php

echo generateReleaseName();
```
